### ISSUE TITLE
!commands crashes bot, but still produces output

### ISSUE THREAD

**Issue by ch1pset** [tipdaddy78/yook_discord_bot#4]
The following is the error message:
```
command.js:32
line 32:    for(let i = 0; i < cmdList[cmd].channel.length; i++) {
                                                               ^
TypeError: Cannot read property 'channel' of undefined
    at Cmd.checkChannel (command.js:32:41)
    at Cmd.parseInput (command.js:48:21)
    at Client.bot.on.msg (bot.js:23:9)

**Comment by ch1pset** [comment]
Removed !commands and moved it's functionality to !help. This resolved the issue indirectly.
