### ISSUE TITLE
Empty message being sent in cmdHelp() function

### ISSUE THREAD

**Issue by ch1pset** [tipdaddy78/yook_discord_bot#5]
Replacing: `if(this.cmdExists(cmd)) {`
with: `if(cmdList.hasOwnProperty(cmd)) {`
and adding: `else { this.sendMessage(this.cmdHelp('help')); }`
Results in the following error:
```
(node:6460) UnhandledPromiseRejectionWarning: DiscordAPIError: Cannot send an empty message
    at item.request.gen.end (C:\Users\Josh\Programming\Projects\Atom\Discord\node_modules\discord.js\src\client\rest\RequestHandlers
\Sequential.js:79:15)
    at then (C:\Users\Josh\Programming\Projects\Atom\Discord\node_modules\snekfetch\src\index.js:215:21)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:6460) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an asy
nc function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:6460) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are no
t handled will terminate the Node.js process with a non-zero exit code.
```
Not sure where an empty message is being sent, but this does not crash the bot. Also, `cmdExists()` sends a help message itself. Using the `hasOwnProperty` method reduces overhead, and increases flexibility of `cmdHelp()`

**Comment by ch1pset** [comment]
Fixed by replacing: `if(cmdList.hasOwnProperty(cmd)) {`
with: `let cmd = cmdList.hasOwnProperty(cmd_in)? cmd_in:'help';`
and refactoring: `cmdHelp(cmd)` to `cmdHelp(cmd_in)`
