### ISSUE TITLE
Unhandled WebSocketConnection Error

### ISSUE THREAD

**Issue by ch1pset** [tipdaddy78/yook_discord_bot#9]
```
Trace: { Error [ERR_UNHANDLED_ERROR]: Unhandled error. ([object Object])
    at Client.emit (events.js:177:17)
    at WebSocketConnection.onError (..\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:374:17)
    at WebSocket.onError (..\node_modules\discord.js\node_modules\ws\lib\event-target.js:128:16)
    at WebSocket.emit (events.js:188:13)
    at _receiver.cleanup (..\node_modules\discord.js\node_modules\ws\lib\websocket.js:211:14)
    at Receiver.cleanup (..\node_modules\discord.js\node_modules\ws\lib\receiver.js:557:13)
    at WebSocket.finalize (..\node_modules\discord.js\node_modules\ws\lib\websocket.js:206:20)
    at TLSSocket.emit (events.js:188:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
  context:
   ErrorEvent {
     target:
      WebSocket {
        _events: [Object],
        _eventsCount: 4,
        _maxListeners: undefined,
        readyState: 2,
        protocol: '',
        _binaryType: 'nodebuffer',
        _finalize: [Function: bound finalize],
        _closeFrameReceived: false,
        _closeFrameSent: false,
        _closeMessage: '',
        _closeTimer: null,
        _finalized: true,
        _closeCode: 1006,
        _extensions: {},
        _isServer: false,
        _receiver: [Receiver],
        _sender: [Sender],
        _socket: [TLSSocket],
        _error: null,
        url: 'wss://gateway.discord.gg/?v=6&encoding=json',
        _req: null },
     type: 'error',
     message: 'read ECONNRESET',
     error:
      { Error: read ECONNRESET
          at TLSWrap.onStreamRead (internal/stream_base_commons.js:162:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' } } }
    at Logger.errToFile (.\yook_discord_bot\Logs\Logger.js:45:30)
    at process.on.msg (.\yook_discord_bot\bot\bot.js:64:16)
    at process.emit (events.js:188:13)
    at process._fatalException (internal/bootstrap/node.js:627:27)
```

**Comment by ch1pset** [comment]
Not quite sure how to handle this, ideally, we should attempt a reconnect or potentially restart the bot when the unhandled exception is thrown.

**Comment by ch1pset** [comment]
Now hosting bot on an always-on embedded device(RPI). The issue doesn't seem to be coming up anymore as I suspect it was due to my PC going to sleep and terminating the connection to discord. Still want to implement a way for the bot to restart itself.

**Comment by ch1pset** [comment]
Bot can now reconnect automatically if it's been disconnected. It can still crash, which is another issue to be resolved.
